### ISSUE TITLE
Qt5 meta-issues

### ISSUE THREAD

**Issue by mingwandroid** [ContinuumIO/anaconda-issues#1136]
I want to use this to keep track of changes for Qt5 itself, if you want to re-use this issue for the PyQt side of things too then that's fine, we'll keep this comment for Qt5 itself though and I'll add suggestions people make in subsequent comments (we can't edit each others' comments can we?)

- [ ] Update to 5.6.2 (or whichever version is latest once work commences)
- [ ] Add shortcuts for Qt gui tools https://github.com/ContinuumIO/anaconda-issues/issues/606
- [ ] Consider adding documentation packages (split-packages?)

**Comment by ccordoba12** [comment]
I think we should schedule this for Anaconda 4.3.

**Comment by mingwandroid** [comment]
Maybe, it will depend on the quality of 5.6.0 more than anything.

**Comment by ccordoba12** [comment]
Right, let's wait then for 5.6.2 to start working on this (as you said before :-)
