### ISSUE TITLE
miniconda installer 23.5.1 or roadmap for future releases

### ISSUE THREAD

**Issue by twenty-19** [ContinuumIO/anaconda-issues#13214]
### Checklist

- [X] I added a descriptive title (including the requested package **name**, **version**, and **platform**).
- [X] I searched the defaults channels ([Python](https://repo.anaconda.com/pkgs/main/) and [R](https://repo.anaconda.com/pkgs/r/)) and did not find the package I'm requesting.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and did not find a duplicate request for this package.

### Request type

- [ ] New (i.e. no versions of this package currently exist on repo.anaconda.com)
- [X] Update (i.e. older versions of this package exist and I'm requesting an updated version)
- [ ] Rebuild (i.e. something is wrong with an existing version of this package and it needs to be rebuilt)

### Name

miniconda installer

### Version

23.5.x

### Platform(s)

linux-64

### Reason for this request

Trying to determine if a new release of the miniconda installer is in the works, is there a roadmap for future releases?

Something like https://github.com/conda/conda/milestones ?

**Comment by twenty-19** [comment]
https://conda.org/blog/
