### ISSUE TITLE
sha256sum of the anaconda miniconda .sh file for linux does not match #14339

### ISSUE THREAD

**Issue by jerabaul29** [ContinuumIO/anaconda-issues#13433]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [ ] A conda package (built by Anaconda)
- [X] Anaconda Distribution (formerly Anaconda Individual Edition)
- [X] Miniconda
- [ ] Anaconda.org

### What happened?

I install anaconda / miniconda in some container, using the following code:

```
RUN wget --https-only https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
# this is hardcoded for now; retrieved from https://docs.anaconda.com/miniconda/
# TODO: find a programmatic way to retrieve the hash? or just update by hand when it breaks?
RUN echo "33442cd3813df33dcbb4a932b938ee95398be98344dff4c30f7e757cd2110e4f Miniconda3-latest-Linux-x86_64.sh" | sha256sum --check
```

this was working yesterday, but today I get a mismatch in the sha256sum:

```
Error: building at STEP "RUN echo "33442cd3813df33dcbb4a932b938ee95398be98344dff4c30f7e757cd2110e4f Miniconda3-latest-Linux-x86_64.sh" | sha256sum --check": while running runtime: exit status 1
```

I also tried by hand downloading the latest [Miniconda3 Linux 64-bit](https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh) installer from https://docs.anaconda.com/miniconda/ . I get the following sha256sum, that does not match the expected sha256sum:

```
✔ pc6012:~/Downloads> wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
...
✔ pc6012:~/Downloads> echo "33442cd3813df33dcbb4a932b938ee95398be98344dff4c30f7e757cd2110e4f Miniconda3-latest-Linux-x86_64.sh" | sha256sum --check
Miniconda3-latest-Linux-x86_64.sh: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
```

Any idea why? If I should report it somewhere else, where should I report it?

### Expected behavior or outcome

The checksum should match.

### Conda info

```shell
This is not relevant, happens before conda gets installed.
```

**Comment by jerabaul29** [comment]
Since the issue popped up yesterday, the sha256sum has been updated on the website, so this works again :) .
